USE dbstg;

CREATE TABLE PROVINCIAS_EXT (
    ID_PROVINCIA VARCHAR (10) NOT NULL,
    NOMBRE_PROVINCIA VARCHAR (50) NOT NULL
);

CREATE TABLE SERVICIOS_EXT ( 
    ID_SERVICIO VARCHAR (10) NOT NULL,
    DESCRIPCION_SERVICIO VARCHAR (50) NOT NULL,
    VALOR_SERVICIO VARCHAR (10) NOT NULL,
    TIEMPO_SUBSCRIPCION VARCHAR (5) NOT NULL,
    BENEFICIOS_SERVICIO VARCHAR (100) NOT NULL
);

CREATE TABLE MOTIVOS_EXT ( 
    ID_MOTIVO VARCHAR (10) NOT NULL,
    DESCRIPCION_MOTIVO VARCHAR (100) NOT NULL
);

CREATE TABLE CLIENTES_EXT ( 
    ID_CLIENTE VARCHAR (10) NOT NULL,
    ID_PROVINCIA VARCHAR (10) NOT NULL,
    NOMBRE_CLIENTE VARCHAR (50) NOT NULL,
    TIPO_CLIENTE VARCHAR (10) NOT NULL
);

CREATE TABLE ORDENES_EXT ( 
    ID_ORDEN VARCHAR (10) NOT NULL,
    ID_CLIENTE VARCHAR (10) NOT NULL,
    ID_SERVICIO VARCHAR (10) NOT NULL,
    ID_PROVINCIA VARCHAR (10) NOT NULL,
    ID_MOTIVO VARCHAR (10) NOT NULL,
    ESTADO_ORDEN VARCHAR (10) NOT NULL,
    FECHA_ADQUISICION VARCHAR (10) NOT NULL
);

CREATE TABLE PREMIOS_EXT (
    ID_PREMIO VARCHAR (10) NOT NULL,
    ID_CLIENTE VARCHAR (10) NOT NULL,
    DESCRIPCION_PREMIO VARCHAR (100) NOT NULL,
    VALOR_PREMIO VARCHAR (10) NOT NULL,
    CANJEADO VARCHAR (1) NOT NULL
);