USE dbstg;

CREATE TABLE PROCESOS_ETL (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    FECHA_EJECUCION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE PROVINCIAS_TRA (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_PROVINCIA INTEGER NOT NULL,
    NOMBRE_PROVINCIA VARCHAR (50) NOT NULL,
    ETL_PROC_ID INTEGER NOT NULL
);

CREATE TABLE SERVICIOS_TRA (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_SERVICIO INTEGER NOT NULL,
    DESCRIPCION_SERVICIO VARCHAR (50) NOT NULL,
    VALOR_SERVICIO DECIMAL (8,2) NOT NULL,
    TIEMPO_SUBSCRIPCION INTEGER (5) NOT NULL,
    BENEFICIOS_SERVICIO VARCHAR (100) NOT NULL,
    ETL_PROC_ID INTEGER NOT NULL
);

CREATE TABLE MOTIVOS_TRA (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_MOTIVO INTEGER NOT NULL,
    DESCRIPCION_MOTIVO VARCHAR (100) NOT NULL,
    ETL_PROC_ID INTEGER NOT NULL
);

CREATE TABLE CLIENTES_TRA (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_CLIENTE INTEGER NOT NULL,
    ID_PROVINCIA INTEGER NOT NULL,
    NOMBRE_CLIENTE VARCHAR (50) NOT NULL,
    TIPO_CLIENTE VARCHAR (10) NOT NULL,
    ETL_PROC_ID INTEGER NOT NULL
);

CREATE TABLE ORDENES_TRA (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_ORDEN INTEGER NOT NULL,
    ID_CLIENTE INTEGER NOT NULL,
    ID_SERVICIO INTEGER NOT NULL,
    ID_PROVINCIA INTEGER NOT NULL,
    ID_MOTIVO INTEGER NOT NULL,
    ESTADO_ORDEN VARCHAR (10) NOT NULL,
    FECHA_ADQUISICION DATE NOT NULL,
    ETL_PROC_ID INTEGER NOT NULL
);

CREATE TABLE PREMIOS_TRA (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_PREMIO INTEGER NOT NULL,
    ID_CLIENTE INTEGER NOT NULL,
    DESCRIPCION_PREMIO VARCHAR (100) NOT NULL,
    VALOR_PREMIO DECIMAL (8,2) NOT NULL,
    CANJEADO VARCHAR (1) NOT NULL
);
